### ISSUE TITLE
Grouping nodes in subgraph seems not to work for speech recognizer nodes

### ISSUE THREAD

**Issue by kastein** [dialogos-project/dialogos#150] opened 2019-01-11 12:22 UTC
I tried to group nodes together in a subgraph by marking them and selecting "Knoten zusammenfassen". Everytime I want to include a speech recognizer node I get an error message. For the other nodes for which I tried it, it seems to work.

<img width="367" alt="cannotgroup" src="https://user-images.githubusercontent.com/36165516/51033437-9da1f400-15a3-11e9-9985-4425e94e2cff.PNG">

I also got once this error message although the first node marked didn't have more than one incoming edge

<img width="917" alt="cantgroup" src="https://user-images.githubusercontent.com/36165516/51033481-c924de80-15a3-11e9-890e-99aad1043903.PNG">

Unfortunately I couldn't reproduce the second error but for reproducing the first error I include a minimal example.

[cannot group.zip](https://github.com/dialogos-project/dialogos/files/2749568/cannot.group.zip)

**Comment by alexanderkoller** [comment] 2019-02-01 10:00
Duplicate of #163 .

**Closed by alexanderkoller** 2019-02-01 10:00 UTC
Labels: duplicate
